services:

  web-service:
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - sentiment-serving
    restart: always

  sentiment-serving:
    build: ./serving
    platform: linux/amd64
    ports:
      - "8083:8080"
    volumes:
      - ~/.djl.ai:/root/.djl.ai
    command: serve -m "sentiment=djl://ai.djl.pytorch/distilbert"
    restart: always
